name: Deploy to Prod

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    name: Deploy para Ambiente Prod
    runs-on: ubuntu-latest

    environment:
      name: prod      # Deve existir o environment 'prod' no repositório (Settings > Environments)

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build e testes
        run: |
          cd devcalc 
          mvn clean package

      - name: Deploy simulado em Prod
        run: |
          echo "Deploy para Prod concluído com sucesso."
