name: Self-Hosted Runner Demo

# Dispara manualmente (workflow_dispatch) ou em push na branch dev/main
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main

jobs:
  self-hosted-test:
    name: Testar no Runner Auto-Hospedado
    runs-on: self-hosted

    steps:
      - name: Verificar identificação do runner
        run: |
          echo "=== Informações do Runner ==="
          uname -a

      - name: Instalar utilitário curl (exemplo de apt)
        if: runner.os == 'Linux'
        run: sudo dnf install -y curl

      - name: Verificar versão do Java
        run: java -version

      - name: Verificar curl
        run: |
          if command -v curl >/dev/null 2>&1; then
            echo "curl instalado com sucesso."
          else
            echo "curl não está instalado."
            exit 1
          fi
